# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# example Azure instance
---
cloud: azure  
tenant: AZURE_PROFILE
project: PROJECT
domain: DOMAIN
application: postgresql
region: AZURE_REGION
cluster: CLUSTER
replica: REPLICA
role: ROLE
dataflow: FLOW
user: USER
image: IMAGE
type: TYPE
root_volume: SIZE
data_volume: SIZE
cidr_block: CIDR_BLOCK
internal_subnet: SUBNET
external_subnet: SUBNET
http_proxy: PROXY
